'use strict'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/components.module.css'

import Layout from '../components/Layout'
import Section from '../components/Section'

export default function Home() {
  return (
    <>
      <Head>
        <title>Hugo Vanhove | Contact</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout path="contact">
        <div className={styles.row_container}>
          hgellop
        </div>
      </Layout>
    </>
  )
}
