import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/components.module.css'

import Layout from '../components/Layout'
import Section from '../components/Section'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout path="index">
          <Section title="Clone de Youtube" month="06" year="2020" path="" />
          <Section title="Polygon RôlePlay" month="06" year="2020" path="" />
          <Section title="Maison des ados virtuelle" month="06" year="2020" path="" />
          <Section title="Rosella tea" month="06" year="2020" path="" />
      </Layout>
    </>
  )
}
