'use strict'
import Head from 'next/head'
import styles from '../styles/components.module.css'
import Typewriter from 'typewriter-effect'

import Layout from '../components/Layout'

export default function Index() {
  return (
    <>
      <Head>
        <title>Hugo Vanhove | Développeur JavaScript Junior</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout path="index">
        <div className={styles.col_container}>
          <section className={styles.hero}>
            <strong>Développeur 
              <Typewriter 
                options={{
                  autoStart: true,
                  loop: true,
                  delay: 100,
                  strings: [
                    'FullStuck Js',
                    'Node',
                    'Next',
                    'React'
                  ]
                }}
              />
            </strong>
            <h1>Hugo Vanhove</h1>
            <div className={styles.scroll}>
              <svg xmlns="http://www.w3.org/2000/svg" width="50" height="101" viewBox="0 0 50 101">
                <g id="Rectangle_17" data-name="Rectangle 17" fill="none" stroke="#000" strokeWidth="2">
                  <rect width="50" height="101" rx="25" stroke="none"/>
                  <rect x="1" y="1" width="48" height="99" rx="24" fill="none"/>
                </g>
              </svg>
              <p>scroll</p>
            </div>
          </section>
          <section className={styles.about}>
            <h2>A propos</h2>
            <p>Bonjour, je m&apos;appelle <a rel='noreferrer noopener' href="https://www.linkedin.com/in/hugo-code/" target='_blank' ><strong className={styles.extern_link}>Hugo Vanhove</strong></a> et je suis un jeune étudiant basé à Paris. J&apos;aime créer de belles applications Web en Node, Next ou React.</p>
            <p>Actuellement à la recherche d&apos;un stage dans le <strong>développement web</strong>.</p>
          </section>
          {/* <section className={styles.services}>
            <h2>Services</h2>
            <div className={styles.services_row}>
              <div>
                <h3>Landing Page</h3>
                <p>Site vitrine en 1 à 3 pages</p>
              </div>
              <div>
                <h3>Application Web</h3>
                <p>Site avec un panel administrateur, base de données</p>
              </div>
              <div>
                <h3>Mailing</h3>
                <p>E-mail compatible</p>
              </div>
            </div>
          </section>
          <section className={styles.portfolio}>
            <h2>Dernier Projets</h2>
          </section> */}
        </div>
      </Layout>
    </>
  )
}
