'use strict'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/components.module.css'
import Typewriter from 'typewriter-effect'
import Layout from '../components/Layout'

export default function Home() {
  return (
    <>
      <Head>
        <title>Hugo Vanhove | Développeur JavaScript Junior</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout path="index">
        <div className={styles.col_container}>
          <section className={styles.hero}>
            <h1>Développeur 
              <Typewriter 
                options={{
                  autoStart: true,
                  loop: true,
                  delay: 100,
                  strings: [
                    'Node',
                    'Next',
                    'React'
                  ]
                }}
              />
            </h1>
            <strong>Hugo Vanhove</strong>
          </section>
          <section className={styles.about}>
            <h2>A propos</h2>
            <p>Bonjour, je m'appelle <strong>Hugo Vanhove</strong> et je suis un jeune étudiant basé à Paris. J'aime créer de belles applications Web en Node, Next ou React.</p>
            <p>Actuellement à la recherche d'un stage dans le <strong>développement web</strong>.</p>
          </section>
          <section className={styles.services}>
            <h2>Services</h2>
            <div className={styles.services_row}>
              <div>
                <h3>Landing Page</h3>
                <p>Site vitrine en 1 à 3 pages</p>
              </div>
              <div>
                <h3>Application Web</h3>
                <p>Site avec un panel administrateur, base de données</p>
              </div>
              <div>
                <h3>Mailing</h3>
                <p>E-mail compatible</p>
              </div>
            </div>
          </section>
          <section className={styles.portfolio}>
            <h2>Dernier Projets</h2>
          </section>
        </div>
      </Layout>
    </>
  )
}
