'use strict'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/components.module.css'

import Layout from '../components/Layout'
import Section from '../components/Section'

import youclone from '../public/img/youclone.png'
import witw from '../public/img/witw.png'
import polygon from '../public/img/polygon.png'
import mailing from '../public/img/mailing.png'
import rosella from '../public/img/rosella.png'
import mdav from '../public/img/mdav.png'
import { useEffect } from 'react'

export default function Home() {
  return (
    <>
      <Head>
        <title>Hugo Vanhove | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout path="portfolio">
        <div className={styles.row_container}>
          <h1>Projets</h1>
          <Section 
            title="YouClone" 
            desc="Clone de youtube ( Next.js )" 
            path="youclone" 
            delay=".1"
            img={youclone} />
          <Section 
            title="Where In The World ?" 
            desc="Intégration d'une API Rest ( Next.js )" 
            path="where-in-the-world" 
            delay=".2"
            img={witw} />
          <Section 
            title="Polygon RôlePlay" 
            desc="Forum pour le jeu Gmod ( Node.js )" 
            path="polygon" 
            delay=".3"
            img={polygon} />
          <Section 
            title="Maison des ados virtuelle" 
            desc="Site de prise de rendez-vous ( Node.js )" 
            path="mdav" 
            delay=".4"
            img={mdav} />
          <Section 
            title="Mailing TOEIC" 
            desc="Mail en XHTMl1" 
            path="rosella-tea" 
            delay=".5"
            img={mailing} />
          <Section 
            title="Rosella tea" 
            desc="Landing page" 
            path="rosella-tea" 
            delay=".5"
            img={rosella} />
            <h2>Autres projets</h2>
            <ul>
              <h3>Intégration Web</h3>
              <li>
                <a href="https://codepen.io/HugoVanhove/full/oNLNwvZ" target='_blank'>Premier portfolio</a>
              </li>
              <li>
                <a href="https://codepen.io/HugoVanhove/full/qBNNOBy" target='_blank'>Citation aléatoire</a>
              </li>
              <li>
                <a href="https://codepen.io/HugoVanhove/full/poyMdNb" target='_blank'>Documentation</a>
              </li>
            </ul>
            <ul>
              <h3>Front-End</h3>
              <li>
                <a href="https://codepen.io/HugoVanhove/full/YzWWqPE" target='_blank'>Markdown</a>
              </li>
            </ul>
            <ul>
              <h3>Algorithmes</h3>
              <li>
                <a href="https://replit.com/@HugoCode1/Probability-Calculator#README.md" target='_blank'>Calculateur de probabilité</a>
              </li>
              <li>
                <a href="https://replit.com/@HugoCode1/Time-Calculator#README.md" target='_blank'>Calculateur de temps</a>
              </li>
              <li>
                <a href="https://replit.com/@HugoCode1/Arithmetic-Formatter#README.md" target='_blank'>Formateur arithmétique</a>
              </li>
            </ul>
          </div>
      </Layout>
    </>
  )
}
